#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pulseaudio
Version  : 16.1
Release  : 54
URL      : https://freedesktop.org/software/pulseaudio/releases/pulseaudio-16.1.tar.xz
Source0  : https://freedesktop.org/software/pulseaudio/releases/pulseaudio-16.1.tar.xz
Summary  : PulseAudio Client Interface
Group    : Development/Tools
License  : BSD-3-Clause LGPL-2.1
Requires: rtkit
BuildRequires : bluez-dev
BuildRequires : buildreq-meson
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : gdbm-dev32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : intltool-dev
BuildRequires : libX11-dev
BuildRequires : libX11-dev32
BuildRequires : libcap-dev
BuildRequires : libcap-ng-dev
BuildRequires : libcap-ng-dev32
BuildRequires : libsamplerate-dev
BuildRequires : libtool-dev32
BuildRequires : pkgconfig(32ice)
BuildRequires : pkgconfig(32orc-0.4)
BuildRequires : pkgconfig(32sm)
BuildRequires : pkgconfig(32xtst)
BuildRequires : pkgconfig(bash-completion)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(orc-0.4)
BuildRequires : pkgconfig(sm)
BuildRequires : pkgconfig(xtst)
BuildRequires : sbc-dev
BuildRequires : speex-dev
BuildRequires : speexdsp-dev
Patch1: 0001-Support-a-stateless-configuration.patch
Patch2: lessfence.patch
Patch3: memfd.patch

%description
PULSEAUDIO SOUND SERVER
WEB SITE:
http://pulseaudio.org/
GIT:
https://gitlab.freedesktop.org/pulseaudio/pulseaudio.git

%prep
%setup -q -n pulseaudio-16.1
cd %{_builddir}/pulseaudio-16.1
%patch1 -p1
%patch2 -p1
%patch3 -p1
pushd ..
cp -a pulseaudio-16.1 build32
popd
pushd ..
cp -a pulseaudio-16.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672194917
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -Ofast -falign-functions=32 -fno-lto -fno-semantic-interposition -mprefer-vector-width=512 "
export FCFLAGS="$FFLAGS -Ofast -falign-functions=32 -fno-lto -fno-semantic-interposition -mprefer-vector-width=512 "
export FFLAGS="$FFLAGS -Ofast -falign-functions=32 -fno-lto -fno-semantic-interposition -mprefer-vector-width=512 "
export CXXFLAGS="$CXXFLAGS -Ofast -falign-functions=32 -fno-lto -fno-semantic-interposition -mprefer-vector-width=512 "
%autogen --disable-static --with-udev-rules-dir=/usr/lib/udev/rules.d \
--enable-orc \
--with-speex \
--enable-bluez5 \
--disable-bluez4 \
--disable-bluez5-ofono-headset
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%autogen --disable-static --with-udev-rules-dir=/usr/lib/udev/rules.d \
--enable-orc \
--with-speex \
--enable-bluez5 \
--disable-bluez4 \
--disable-bluez5-ofono-headset --without-fftw \
--disable-gtk3 \
--without-speex \
--without-caps \
--disable-bluez5 \
--disable-bluez4 --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
%autogen --disable-static --with-udev-rules-dir=/usr/lib/udev/rules.d \
--enable-orc \
--with-speex \
--enable-bluez5 \
--disable-bluez4 \
--disable-bluez5-ofono-headset
make  %{?_smp_mflags}
popd
%install
export SOURCE_DATE_EPOCH=1672194917
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pulseaudio
cp %{_builddir}/pulseaudio-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pulseaudio/146b824cf04e121da67545caff4ede65bbbb3936
cp %{_builddir}/pulseaudio-%{version}/src/pulsecore/filter/LICENSE.WEBKIT %{buildroot}/usr/share/package-licenses/pulseaudio/24b8a642abc0e34765a795aef5ce10475e17574b
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
pushd ../buildavx2/
%make_install_v3
popd
%make_install
## install_append content
rm -rf %{buildroot}%{_datadir}/vala
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
