#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v21
# autospec commit: 8b93847
#
Name     : pulseaudio
Version  : 17.0
Release  : 59
URL      : https://www.freedesktop.org/software/pulseaudio/releases/pulseaudio-17.0.tar.gz
Source0  : https://www.freedesktop.org/software/pulseaudio/releases/pulseaudio-17.0.tar.gz
Summary  : PulseAudio GLib 2.0 Main Loop Wrapper
Group    : Development/Tools
License  : BSD-3-Clause LGPL-2.1
Requires: pulseaudio-bin = %{version}-%{release}
Requires: pulseaudio-data = %{version}-%{release}
Requires: pulseaudio-lib = %{version}-%{release}
Requires: pulseaudio-license = %{version}-%{release}
Requires: pulseaudio-locales = %{version}-%{release}
Requires: pulseaudio-man = %{version}-%{release}
Requires: pulseaudio-services = %{version}-%{release}
Requires: rtkit
BuildRequires : bluez-dev
BuildRequires : buildreq-meson
BuildRequires : dbus-dev
BuildRequires : desktop-file-utils
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : gdbm-dev32
BuildRequires : glib-dev
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : gstreamer-dev
BuildRequires : intltool-dev
BuildRequires : libX11-dev
BuildRequires : libX11-dev32
BuildRequires : libcap-dev
BuildRequires : libcap-dev32
BuildRequires : libcap-ng-dev
BuildRequires : libcap-ng-dev32
BuildRequires : libsamplerate-dev
BuildRequires : libsndfile-dev
BuildRequires : libtool-dev32
BuildRequires : openssl-dev
BuildRequires : pkgconfig(32alsa)
BuildRequires : pkgconfig(32check)
BuildRequires : pkgconfig(32dbus-1)
BuildRequires : pkgconfig(32glib-2.0)
BuildRequires : pkgconfig(32ice)
BuildRequires : pkgconfig(32libsystemd)
BuildRequires : pkgconfig(32orc-0.4)
BuildRequires : pkgconfig(32sm)
BuildRequires : pkgconfig(32sndfile)
BuildRequires : pkgconfig(32xtst)
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(bash-completion)
BuildRequires : pkgconfig(check)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(fftw3f)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gstreamer-1.0)
BuildRequires : pkgconfig(gstreamer-app-1.0)
BuildRequires : pkgconfig(gstreamer-rtp-1.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(orc-0.4)
BuildRequires : pkgconfig(sm)
BuildRequires : pkgconfig(sndfile)
BuildRequires : pkgconfig(systemd)
BuildRequires : pkgconfig(xtst)
BuildRequires : sbc-dev
BuildRequires : speex-dev
BuildRequires : speexdsp-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
PULSEAUDIO SOUND SERVER
WEB SITE:
http://pulseaudio.org/
GIT:
https://gitlab.freedesktop.org/pulseaudio/pulseaudio.git

%package bin
Summary: bin components for the pulseaudio package.
Group: Binaries
Requires: pulseaudio-data = %{version}-%{release}
Requires: pulseaudio-license = %{version}-%{release}
Requires: pulseaudio-services = %{version}-%{release}

%description bin
bin components for the pulseaudio package.


%package data
Summary: data components for the pulseaudio package.
Group: Data

%description data
data components for the pulseaudio package.


%package dev
Summary: dev components for the pulseaudio package.
Group: Development
Requires: pulseaudio-lib = %{version}-%{release}
Requires: pulseaudio-bin = %{version}-%{release}
Requires: pulseaudio-data = %{version}-%{release}
Provides: pulseaudio-devel = %{version}-%{release}
Requires: pulseaudio = %{version}-%{release}

%description dev
dev components for the pulseaudio package.


%package dev32
Summary: dev32 components for the pulseaudio package.
Group: Default
Requires: pulseaudio-lib32 = %{version}-%{release}
Requires: pulseaudio-bin = %{version}-%{release}
Requires: pulseaudio-data = %{version}-%{release}
Requires: pulseaudio-dev = %{version}-%{release}

%description dev32
dev32 components for the pulseaudio package.


%package lib
Summary: lib components for the pulseaudio package.
Group: Libraries
Requires: pulseaudio-data = %{version}-%{release}
Requires: pulseaudio-license = %{version}-%{release}

%description lib
lib components for the pulseaudio package.


%package lib32
Summary: lib32 components for the pulseaudio package.
Group: Default
Requires: pulseaudio-data = %{version}-%{release}
Requires: pulseaudio-license = %{version}-%{release}

%description lib32
lib32 components for the pulseaudio package.


%package license
Summary: license components for the pulseaudio package.
Group: Default

%description license
license components for the pulseaudio package.


%package locales
Summary: locales components for the pulseaudio package.
Group: Default

%description locales
locales components for the pulseaudio package.


%package man
Summary: man components for the pulseaudio package.
Group: Default

%description man
man components for the pulseaudio package.


%package services
Summary: services components for the pulseaudio package.
Group: Systemd services
Requires: systemd

%description services
services components for the pulseaudio package.


%prep
%setup -q -n pulseaudio-17.0
cd %{_builddir}/pulseaudio-17.0
pushd ..
cp -a pulseaudio-17.0 build32
popd
pushd ..
cp -a pulseaudio-17.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1738972821
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dudevrulesdir=/usr/lib/udev/rules.d \
-Dorc=enabled \
-Dspeex=enabled \
-Dbluez5=enabled \
-Dbluez5-ofono-headset=false \
-Ddatabase=gdbm \
-Dlirc=disabled \
-Delogind=disabled \
-Dwebrtc-aec=disabled \
-Ddoxygen=false  builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dudevrulesdir=/usr/lib/udev/rules.d \
-Dorc=enabled \
-Dspeex=enabled \
-Dbluez5=enabled \
-Dbluez5-ofono-headset=false \
-Ddatabase=gdbm \
-Dlirc=disabled \
-Delogind=disabled \
-Dwebrtc-aec=disabled \
-Ddoxygen=false  builddiravx2
ninja -v -C builddiravx2
pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
ASFLAGS="${CLEAR_INTERMEDIATE_ASFLAGS}${CLEAR_INTERMEDIATE_ASFLAGS:+ }--32"
CFLAGS="${CLEAR_INTERMEDIATE_CFLAGS}${CLEAR_INTERMEDIATE_CFLAGS:+ }-m32 -mstackrealign"
CXXFLAGS="${CLEAR_INTERMEDIATE_CXXFLAGS}${CLEAR_INTERMEDIATE_CXXFLAGS:+ }-m32 -mstackrealign"
LDFLAGS="${CLEAR_INTERMEDIATE_LDFLAGS}${CLEAR_INTERMEDIATE_LDFLAGS:+ }-m32 -mstackrealign"
meson --libdir=lib32 --prefix=/usr --buildtype=plain -Dudevrulesdir=/usr/lib/udev/rules.d \
-Dorc=enabled \
-Dspeex=enabled \
-Dbluez5=enabled \
-Dbluez5-ofono-headset=false \
-Ddatabase=gdbm \
-Dlirc=disabled \
-Delogind=disabled \
-Dwebrtc-aec=disabled \
-Ddoxygen=false -Dfftw=disabled \
-Dspeex=disabled \
-Dbluez5=disabled \
-Ddatabase=gdbm \
-Dlirc=disabled \
-Delogind=disabled \
-Dwebrtc-aec=disabled \
-Ddoxygen=false \
-Dgstreamer=disabled \
-Dopenssl=disabled \
-Dgtk=disabled builddir
ninja -v -C builddir
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs || :
cd ../build32;
meson test -C builddir --print-errorlogs || : || :
cd ../buildavx2;
meson test -C builddir --print-errorlogs || : || :

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/pulseaudio
cp %{_builddir}/pulseaudio-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pulseaudio/146b824cf04e121da67545caff4ede65bbbb3936 || :
cp %{_builddir}/pulseaudio-%{version}/src/pulsecore/filter/LICENSE.WEBKIT %{buildroot}/usr/share/package-licenses/pulseaudio/24b8a642abc0e34765a795aef5ce10475e17574b || :
pushd ../build32/
DESTDIR=%{buildroot} ninja -C builddir install
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang pulseaudio
## Remove excluded files
rm -f %{buildroot}*/usr/bin/esdcompat
rm -f %{buildroot}*/usr/bin/pa-info
rm -f %{buildroot}*/usr/bin/pacmd
rm -f %{buildroot}*/usr/bin/pasuspender
rm -f %{buildroot}*/usr/bin/pax11publish
rm -f %{buildroot}*/usr/bin/pulseaudio
rm -f %{buildroot}*/usr/bin/qpaeq
rm -f %{buildroot}*/usr/bin/start-pulseaudio-x11
rm -f %{buildroot}*/usr/lib/systemd/user/pulseaudio.service
rm -f %{buildroot}*/usr/lib/systemd/user/pulseaudio.socket
rm -f %{buildroot}*/usr/lib/udev/rules.d/90-pulseaudio.rules
rm -f %{buildroot}*/usr/libexec/pulse/gsettings-helper
rm -f %{buildroot}*/usr/share/GConf/gsettings/pulseaudio.convert
rm -f %{buildroot}*/usr/share/bash-completion/completions/pacmd
rm -f %{buildroot}*/usr/share/bash-completion/completions/pasuspender
rm -f %{buildroot}*/usr/share/bash-completion/completions/pulseaudio
rm -f %{buildroot}*/usr/share/dbus-1/system.d/pulseaudio-system.conf
rm -f %{buildroot}*/usr/share/glib-2.0/schemas/org.freedesktop.pulseaudio.gschema.xml
rm -f %{buildroot}*/usr/share/man/man1/esdcompat.1
rm -f %{buildroot}*/usr/share/man/man1/pacmd.1
rm -f %{buildroot}*/usr/share/man/man1/pasuspender.1
rm -f %{buildroot}*/usr/share/man/man1/pax11publish.1
rm -f %{buildroot}*/usr/share/man/man1/pulseaudio.1
rm -f %{buildroot}*/usr/share/man/man1/start-pulseaudio-x11.1
rm -f %{buildroot}*/usr/share/man/man5/default.pa.5
rm -f %{buildroot}*/usr/share/man/man5/pulse-cli-syntax.5
rm -f %{buildroot}*/usr/share/man/man5/pulse-daemon.conf.5
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-input-aux.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-input-dock-mic.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-input-fm.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-input-front-mic.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-input-headphone-mic.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-input-headset-mic.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-input-internal-mic-always.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-input-internal-mic.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-input-linein.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-input-mic-line.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-input-mic.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-input-mic.conf.common
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-input-rear-mic.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-input-tvtuner.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-input-video.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-input.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-input.conf.common
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-output-headphones-2.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-output-headphones.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-output-lineout.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-output-mono.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-output-speaker-always.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-output-speaker.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-output.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/analog-output.conf.common
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/hdmi-output-0.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/hdmi-output-1.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/hdmi-output-2.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/hdmi-output-3.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/hdmi-output-4.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/hdmi-output-5.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/hdmi-output-6.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/hdmi-output-7.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/iec958-stereo-input.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/iec958-stereo-output.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/steelseries-arctis-output-chat-common.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/steelseries-arctis-output-game-common.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/usb-gaming-headset-input.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/usb-gaming-headset-output-mono.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/paths/usb-gaming-headset-output-stereo.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/profile-sets/audigy.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/profile-sets/cmedia-high-speed-true-hdaudio.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/profile-sets/default.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/profile-sets/dell-dock-tb16-usb-audio.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/profile-sets/force-speaker-and-int-mic.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/profile-sets/force-speaker.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/profile-sets/kinect-audio.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/profile-sets/maudio-fasttrack-pro.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/profile-sets/native-instruments-audio4dj.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/profile-sets/native-instruments-audio8dj.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/profile-sets/native-instruments-korecontroller.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/profile-sets/native-instruments-traktor-audio10.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/profile-sets/native-instruments-traktor-audio2.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/profile-sets/native-instruments-traktor-audio6.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/profile-sets/native-instruments-traktorkontrol-s4.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/profile-sets/sb-omni-surround-5.1.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/profile-sets/steelseries-arctis-common-usb-audio.conf
rm -f %{buildroot}*/usr/share/pulseaudio/alsa-mixer/profile-sets/usb-gaming-headset.conf
rm -f %{buildroot}*/usr/share/pulseaudio/daemon.conf
rm -f %{buildroot}*/usr/share/pulseaudio/default.pa
rm -f %{buildroot}*/usr/share/pulseaudio/system.pa
rm -f %{buildroot}*/usr/share/xdg/autostart/pulseaudio.desktop
rm -f %{buildroot}*/usr/share/xdg/autostart/pulseaudio.desktop
rm -f %{buildroot}*/usr/share/zsh/site-functions/_pulseaudio
## install_append content
rm -rf %{buildroot}*/%{_datadir}/vala
rm -fr %{buildroot}*//usr/lib32/pulse-*
rm -fr %{buildroot}*//usr/lib64/pulse-*
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/pacat
/V3/usr/bin/pactl
/usr/bin/pacat
/usr/bin/pactl
/usr/bin/padsp
/usr/bin/pamon
/usr/bin/paplay
/usr/bin/parec
/usr/bin/parecord

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/pacat
/usr/share/bash-completion/completions/pactl
/usr/share/bash-completion/completions/padsp
/usr/share/bash-completion/completions/paplay
/usr/share/bash-completion/completions/parec
/usr/share/bash-completion/completions/parecord
/usr/share/pulseaudio/alsa-mixer/paths/analog-output-chat.conf
/usr/share/pulseaudio/alsa-mixer/paths/hdmi-output-10.conf
/usr/share/pulseaudio/alsa-mixer/paths/hdmi-output-8.conf
/usr/share/pulseaudio/alsa-mixer/paths/hdmi-output-9.conf
/usr/share/pulseaudio/alsa-mixer/paths/virtual-surround-7.1.conf
/usr/share/pulseaudio/alsa-mixer/profile-sets/asus-xonar-se.conf
/usr/share/pulseaudio/alsa-mixer/profile-sets/hp-tbt-dock-120w-g2.conf
/usr/share/pulseaudio/alsa-mixer/profile-sets/hp-tbt-dock-audio-module.conf
/usr/share/pulseaudio/alsa-mixer/profile-sets/native-instruments-komplete-audio6.conf
/usr/share/pulseaudio/alsa-mixer/profile-sets/sennheiser-gsx.conf
/usr/share/pulseaudio/alsa-mixer/profile-sets/simple-headphones-mic.conf
/usr/share/pulseaudio/alsa-mixer/profile-sets/texas-instruments-pcm2902.conf

%files dev
%defattr(-,root,root,-)
/usr/include/pulse/cdecl.h
/usr/include/pulse/channelmap.h
/usr/include/pulse/context.h
/usr/include/pulse/def.h
/usr/include/pulse/direction.h
/usr/include/pulse/error.h
/usr/include/pulse/ext-device-manager.h
/usr/include/pulse/ext-device-restore.h
/usr/include/pulse/ext-stream-restore.h
/usr/include/pulse/format.h
/usr/include/pulse/gccmacro.h
/usr/include/pulse/glib-mainloop.h
/usr/include/pulse/introspect.h
/usr/include/pulse/mainloop-api.h
/usr/include/pulse/mainloop-signal.h
/usr/include/pulse/mainloop.h
/usr/include/pulse/operation.h
/usr/include/pulse/proplist.h
/usr/include/pulse/pulseaudio.h
/usr/include/pulse/rtclock.h
/usr/include/pulse/sample.h
/usr/include/pulse/scache.h
/usr/include/pulse/simple.h
/usr/include/pulse/stream.h
/usr/include/pulse/subscribe.h
/usr/include/pulse/thread-mainloop.h
/usr/include/pulse/timeval.h
/usr/include/pulse/utf8.h
/usr/include/pulse/util.h
/usr/include/pulse/version.h
/usr/include/pulse/volume.h
/usr/include/pulse/xmalloc.h
/usr/lib64/cmake/PulseAudio/PulseAudioConfig.cmake
/usr/lib64/cmake/PulseAudio/PulseAudioConfigVersion.cmake
/usr/lib64/libpulse-mainloop-glib.so
/usr/lib64/libpulse-simple.so
/usr/lib64/libpulse.so
/usr/lib64/pkgconfig/libpulse-mainloop-glib.pc
/usr/lib64/pkgconfig/libpulse-simple.pc
/usr/lib64/pkgconfig/libpulse.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/cmake/PulseAudio/PulseAudioConfig.cmake
/usr/lib32/cmake/PulseAudio/PulseAudioConfigVersion.cmake
/usr/lib32/libpulse-mainloop-glib.so
/usr/lib32/libpulse-simple.so
/usr/lib32/libpulse.so
/usr/lib32/pkgconfig/32libpulse-mainloop-glib.pc
/usr/lib32/pkgconfig/32libpulse-simple.pc
/usr/lib32/pkgconfig/32libpulse.pc
/usr/lib32/pkgconfig/libpulse-mainloop-glib.pc
/usr/lib32/pkgconfig/libpulse-simple.pc
/usr/lib32/pkgconfig/libpulse.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libpulse-mainloop-glib.so.0.0.6
/V3/usr/lib64/libpulse-simple.so.0.1.1
/V3/usr/lib64/libpulse.so.0.24.3
/V3/usr/lib64/pulseaudio/libpulsecommon-17.0.so
/V3/usr/lib64/pulseaudio/libpulsecore-17.0.so
/V3/usr/lib64/pulseaudio/libpulsedsp.so
/V3/usr/lib64/pulseaudio/modules/libalsa-util.so
/V3/usr/lib64/pulseaudio/modules/libbluez5-util.so
/V3/usr/lib64/pulseaudio/modules/libcli.so
/V3/usr/lib64/pulseaudio/modules/liboss-util.so
/V3/usr/lib64/pulseaudio/modules/libprotocol-cli.so
/V3/usr/lib64/pulseaudio/modules/libprotocol-http.so
/V3/usr/lib64/pulseaudio/modules/libprotocol-native.so
/V3/usr/lib64/pulseaudio/modules/libprotocol-simple.so
/V3/usr/lib64/pulseaudio/modules/libraop.so
/V3/usr/lib64/pulseaudio/modules/librtp.so
/V3/usr/lib64/pulseaudio/modules/module-allow-passthrough.so
/V3/usr/lib64/pulseaudio/modules/module-alsa-card.so
/V3/usr/lib64/pulseaudio/modules/module-alsa-sink.so
/V3/usr/lib64/pulseaudio/modules/module-alsa-source.so
/V3/usr/lib64/pulseaudio/modules/module-always-sink.so
/V3/usr/lib64/pulseaudio/modules/module-always-source.so
/V3/usr/lib64/pulseaudio/modules/module-augment-properties.so
/V3/usr/lib64/pulseaudio/modules/module-bluetooth-discover.so
/V3/usr/lib64/pulseaudio/modules/module-bluetooth-policy.so
/V3/usr/lib64/pulseaudio/modules/module-bluez5-device.so
/V3/usr/lib64/pulseaudio/modules/module-bluez5-discover.so
/V3/usr/lib64/pulseaudio/modules/module-card-restore.so
/V3/usr/lib64/pulseaudio/modules/module-cli-protocol-tcp.so
/V3/usr/lib64/pulseaudio/modules/module-cli-protocol-unix.so
/V3/usr/lib64/pulseaudio/modules/module-cli.so
/V3/usr/lib64/pulseaudio/modules/module-combine-sink.so
/V3/usr/lib64/pulseaudio/modules/module-combine.so
/V3/usr/lib64/pulseaudio/modules/module-console-kit.so
/V3/usr/lib64/pulseaudio/modules/module-dbus-protocol.so
/V3/usr/lib64/pulseaudio/modules/module-default-device-restore.so
/V3/usr/lib64/pulseaudio/modules/module-detect.so
/V3/usr/lib64/pulseaudio/modules/module-device-manager.so
/V3/usr/lib64/pulseaudio/modules/module-device-restore.so
/V3/usr/lib64/pulseaudio/modules/module-echo-cancel.so
/V3/usr/lib64/pulseaudio/modules/module-equalizer-sink.so
/V3/usr/lib64/pulseaudio/modules/module-filter-apply.so
/V3/usr/lib64/pulseaudio/modules/module-filter-heuristics.so
/V3/usr/lib64/pulseaudio/modules/module-hal-detect.so
/V3/usr/lib64/pulseaudio/modules/module-http-protocol-tcp.so
/V3/usr/lib64/pulseaudio/modules/module-http-protocol-unix.so
/V3/usr/lib64/pulseaudio/modules/module-intended-roles.so
/V3/usr/lib64/pulseaudio/modules/module-ladspa-sink.so
/V3/usr/lib64/pulseaudio/modules/module-loopback.so
/V3/usr/lib64/pulseaudio/modules/module-match.so
/V3/usr/lib64/pulseaudio/modules/module-mmkbd-evdev.so
/V3/usr/lib64/pulseaudio/modules/module-native-protocol-fd.so
/V3/usr/lib64/pulseaudio/modules/module-native-protocol-tcp.so
/V3/usr/lib64/pulseaudio/modules/module-native-protocol-unix.so
/V3/usr/lib64/pulseaudio/modules/module-null-sink.so
/V3/usr/lib64/pulseaudio/modules/module-null-source.so
/V3/usr/lib64/pulseaudio/modules/module-oss.so
/V3/usr/lib64/pulseaudio/modules/module-pipe-sink.so
/V3/usr/lib64/pulseaudio/modules/module-pipe-source.so
/V3/usr/lib64/pulseaudio/modules/module-position-event-sounds.so
/V3/usr/lib64/pulseaudio/modules/module-raop-sink.so
/V3/usr/lib64/pulseaudio/modules/module-remap-sink.so
/V3/usr/lib64/pulseaudio/modules/module-remap-source.so
/V3/usr/lib64/pulseaudio/modules/module-rescue-streams.so
/V3/usr/lib64/pulseaudio/modules/module-role-cork.so
/V3/usr/lib64/pulseaudio/modules/module-role-ducking.so
/V3/usr/lib64/pulseaudio/modules/module-rtp-recv.so
/V3/usr/lib64/pulseaudio/modules/module-rtp-send.so
/V3/usr/lib64/pulseaudio/modules/module-rygel-media-server.so
/V3/usr/lib64/pulseaudio/modules/module-simple-protocol-tcp.so
/V3/usr/lib64/pulseaudio/modules/module-simple-protocol-unix.so
/V3/usr/lib64/pulseaudio/modules/module-sine-source.so
/V3/usr/lib64/pulseaudio/modules/module-sine.so
/V3/usr/lib64/pulseaudio/modules/module-stream-restore.so
/V3/usr/lib64/pulseaudio/modules/module-suspend-on-idle.so
/V3/usr/lib64/pulseaudio/modules/module-switch-on-connect.so
/V3/usr/lib64/pulseaudio/modules/module-switch-on-port-available.so
/V3/usr/lib64/pulseaudio/modules/module-systemd-login.so
/V3/usr/lib64/pulseaudio/modules/module-tunnel-sink-new.so
/V3/usr/lib64/pulseaudio/modules/module-tunnel-sink.so
/V3/usr/lib64/pulseaudio/modules/module-tunnel-source-new.so
/V3/usr/lib64/pulseaudio/modules/module-tunnel-source.so
/V3/usr/lib64/pulseaudio/modules/module-udev-detect.so
/V3/usr/lib64/pulseaudio/modules/module-virtual-sink.so
/V3/usr/lib64/pulseaudio/modules/module-virtual-source.so
/V3/usr/lib64/pulseaudio/modules/module-virtual-surround-sink.so
/V3/usr/lib64/pulseaudio/modules/module-volume-restore.so
/V3/usr/lib64/pulseaudio/modules/module-x11-bell.so
/V3/usr/lib64/pulseaudio/modules/module-x11-cork-request.so
/V3/usr/lib64/pulseaudio/modules/module-x11-publish.so
/V3/usr/lib64/pulseaudio/modules/module-x11-xsmp.so
/usr/lib64/libpulse-mainloop-glib.so.0
/usr/lib64/libpulse-mainloop-glib.so.0.0.6
/usr/lib64/libpulse-simple.so.0
/usr/lib64/libpulse-simple.so.0.1.1
/usr/lib64/libpulse.so.0
/usr/lib64/libpulse.so.0.24.3
/usr/lib64/pulseaudio/libpulsecommon-17.0.so
/usr/lib64/pulseaudio/libpulsecore-17.0.so
/usr/lib64/pulseaudio/libpulsedsp.so
/usr/lib64/pulseaudio/modules/libalsa-util.so
/usr/lib64/pulseaudio/modules/libbluez5-util.so
/usr/lib64/pulseaudio/modules/libcli.so
/usr/lib64/pulseaudio/modules/liboss-util.so
/usr/lib64/pulseaudio/modules/libprotocol-cli.so
/usr/lib64/pulseaudio/modules/libprotocol-http.so
/usr/lib64/pulseaudio/modules/libprotocol-native.so
/usr/lib64/pulseaudio/modules/libprotocol-simple.so
/usr/lib64/pulseaudio/modules/libraop.so
/usr/lib64/pulseaudio/modules/librtp.so
/usr/lib64/pulseaudio/modules/module-allow-passthrough.so
/usr/lib64/pulseaudio/modules/module-alsa-card.so
/usr/lib64/pulseaudio/modules/module-alsa-sink.so
/usr/lib64/pulseaudio/modules/module-alsa-source.so
/usr/lib64/pulseaudio/modules/module-always-sink.so
/usr/lib64/pulseaudio/modules/module-always-source.so
/usr/lib64/pulseaudio/modules/module-augment-properties.so
/usr/lib64/pulseaudio/modules/module-bluetooth-discover.so
/usr/lib64/pulseaudio/modules/module-bluetooth-policy.so
/usr/lib64/pulseaudio/modules/module-bluez5-device.so
/usr/lib64/pulseaudio/modules/module-bluez5-discover.so
/usr/lib64/pulseaudio/modules/module-card-restore.so
/usr/lib64/pulseaudio/modules/module-cli-protocol-tcp.so
/usr/lib64/pulseaudio/modules/module-cli-protocol-unix.so
/usr/lib64/pulseaudio/modules/module-cli.so
/usr/lib64/pulseaudio/modules/module-combine-sink.so
/usr/lib64/pulseaudio/modules/module-combine.so
/usr/lib64/pulseaudio/modules/module-console-kit.so
/usr/lib64/pulseaudio/modules/module-dbus-protocol.so
/usr/lib64/pulseaudio/modules/module-default-device-restore.so
/usr/lib64/pulseaudio/modules/module-detect.so
/usr/lib64/pulseaudio/modules/module-device-manager.so
/usr/lib64/pulseaudio/modules/module-device-restore.so
/usr/lib64/pulseaudio/modules/module-echo-cancel.so
/usr/lib64/pulseaudio/modules/module-equalizer-sink.so
/usr/lib64/pulseaudio/modules/module-filter-apply.so
/usr/lib64/pulseaudio/modules/module-filter-heuristics.so
/usr/lib64/pulseaudio/modules/module-hal-detect.so
/usr/lib64/pulseaudio/modules/module-http-protocol-tcp.so
/usr/lib64/pulseaudio/modules/module-http-protocol-unix.so
/usr/lib64/pulseaudio/modules/module-intended-roles.so
/usr/lib64/pulseaudio/modules/module-ladspa-sink.so
/usr/lib64/pulseaudio/modules/module-loopback.so
/usr/lib64/pulseaudio/modules/module-match.so
/usr/lib64/pulseaudio/modules/module-mmkbd-evdev.so
/usr/lib64/pulseaudio/modules/module-native-protocol-fd.so
/usr/lib64/pulseaudio/modules/module-native-protocol-tcp.so
/usr/lib64/pulseaudio/modules/module-native-protocol-unix.so
/usr/lib64/pulseaudio/modules/module-null-sink.so
/usr/lib64/pulseaudio/modules/module-null-source.so
/usr/lib64/pulseaudio/modules/module-oss.so
/usr/lib64/pulseaudio/modules/module-pipe-sink.so
/usr/lib64/pulseaudio/modules/module-pipe-source.so
/usr/lib64/pulseaudio/modules/module-position-event-sounds.so
/usr/lib64/pulseaudio/modules/module-raop-sink.so
/usr/lib64/pulseaudio/modules/module-remap-sink.so
/usr/lib64/pulseaudio/modules/module-remap-source.so
/usr/lib64/pulseaudio/modules/module-rescue-streams.so
/usr/lib64/pulseaudio/modules/module-role-cork.so
/usr/lib64/pulseaudio/modules/module-role-ducking.so
/usr/lib64/pulseaudio/modules/module-rtp-recv.so
/usr/lib64/pulseaudio/modules/module-rtp-send.so
/usr/lib64/pulseaudio/modules/module-rygel-media-server.so
/usr/lib64/pulseaudio/modules/module-simple-protocol-tcp.so
/usr/lib64/pulseaudio/modules/module-simple-protocol-unix.so
/usr/lib64/pulseaudio/modules/module-sine-source.so
/usr/lib64/pulseaudio/modules/module-sine.so
/usr/lib64/pulseaudio/modules/module-stream-restore.so
/usr/lib64/pulseaudio/modules/module-suspend-on-idle.so
/usr/lib64/pulseaudio/modules/module-switch-on-connect.so
/usr/lib64/pulseaudio/modules/module-switch-on-port-available.so
/usr/lib64/pulseaudio/modules/module-systemd-login.so
/usr/lib64/pulseaudio/modules/module-tunnel-sink-new.so
/usr/lib64/pulseaudio/modules/module-tunnel-sink.so
/usr/lib64/pulseaudio/modules/module-tunnel-source-new.so
/usr/lib64/pulseaudio/modules/module-tunnel-source.so
/usr/lib64/pulseaudio/modules/module-udev-detect.so
/usr/lib64/pulseaudio/modules/module-virtual-sink.so
/usr/lib64/pulseaudio/modules/module-virtual-source.so
/usr/lib64/pulseaudio/modules/module-virtual-surround-sink.so
/usr/lib64/pulseaudio/modules/module-volume-restore.so
/usr/lib64/pulseaudio/modules/module-x11-bell.so
/usr/lib64/pulseaudio/modules/module-x11-cork-request.so
/usr/lib64/pulseaudio/modules/module-x11-publish.so
/usr/lib64/pulseaudio/modules/module-x11-xsmp.so

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libpulse-mainloop-glib.so.0
/usr/lib32/libpulse-mainloop-glib.so.0.0.6
/usr/lib32/libpulse-simple.so.0
/usr/lib32/libpulse-simple.so.0.1.1
/usr/lib32/libpulse.so.0
/usr/lib32/libpulse.so.0.24.3
/usr/lib32/pulseaudio/libpulsecommon-17.0.so
/usr/lib32/pulseaudio/libpulsecore-17.0.so
/usr/lib32/pulseaudio/libpulsedsp.so
/usr/lib32/pulseaudio/modules/libalsa-util.so
/usr/lib32/pulseaudio/modules/libcli.so
/usr/lib32/pulseaudio/modules/liboss-util.so
/usr/lib32/pulseaudio/modules/libprotocol-cli.so
/usr/lib32/pulseaudio/modules/libprotocol-http.so
/usr/lib32/pulseaudio/modules/libprotocol-native.so
/usr/lib32/pulseaudio/modules/libprotocol-simple.so
/usr/lib32/pulseaudio/modules/librtp.so
/usr/lib32/pulseaudio/modules/module-allow-passthrough.so
/usr/lib32/pulseaudio/modules/module-alsa-card.so
/usr/lib32/pulseaudio/modules/module-alsa-sink.so
/usr/lib32/pulseaudio/modules/module-alsa-source.so
/usr/lib32/pulseaudio/modules/module-always-sink.so
/usr/lib32/pulseaudio/modules/module-always-source.so
/usr/lib32/pulseaudio/modules/module-augment-properties.so
/usr/lib32/pulseaudio/modules/module-card-restore.so
/usr/lib32/pulseaudio/modules/module-cli-protocol-tcp.so
/usr/lib32/pulseaudio/modules/module-cli-protocol-unix.so
/usr/lib32/pulseaudio/modules/module-cli.so
/usr/lib32/pulseaudio/modules/module-combine-sink.so
/usr/lib32/pulseaudio/modules/module-combine.so
/usr/lib32/pulseaudio/modules/module-console-kit.so
/usr/lib32/pulseaudio/modules/module-dbus-protocol.so
/usr/lib32/pulseaudio/modules/module-default-device-restore.so
/usr/lib32/pulseaudio/modules/module-detect.so
/usr/lib32/pulseaudio/modules/module-device-manager.so
/usr/lib32/pulseaudio/modules/module-device-restore.so
/usr/lib32/pulseaudio/modules/module-echo-cancel.so
/usr/lib32/pulseaudio/modules/module-filter-apply.so
/usr/lib32/pulseaudio/modules/module-filter-heuristics.so
/usr/lib32/pulseaudio/modules/module-hal-detect.so
/usr/lib32/pulseaudio/modules/module-http-protocol-tcp.so
/usr/lib32/pulseaudio/modules/module-http-protocol-unix.so
/usr/lib32/pulseaudio/modules/module-intended-roles.so
/usr/lib32/pulseaudio/modules/module-ladspa-sink.so
/usr/lib32/pulseaudio/modules/module-loopback.so
/usr/lib32/pulseaudio/modules/module-match.so
/usr/lib32/pulseaudio/modules/module-mmkbd-evdev.so
/usr/lib32/pulseaudio/modules/module-native-protocol-fd.so
/usr/lib32/pulseaudio/modules/module-native-protocol-tcp.so
/usr/lib32/pulseaudio/modules/module-native-protocol-unix.so
/usr/lib32/pulseaudio/modules/module-null-sink.so
/usr/lib32/pulseaudio/modules/module-null-source.so
/usr/lib32/pulseaudio/modules/module-oss.so
/usr/lib32/pulseaudio/modules/module-pipe-sink.so
/usr/lib32/pulseaudio/modules/module-pipe-source.so
/usr/lib32/pulseaudio/modules/module-position-event-sounds.so
/usr/lib32/pulseaudio/modules/module-remap-sink.so
/usr/lib32/pulseaudio/modules/module-remap-source.so
/usr/lib32/pulseaudio/modules/module-rescue-streams.so
/usr/lib32/pulseaudio/modules/module-role-cork.so
/usr/lib32/pulseaudio/modules/module-role-ducking.so
/usr/lib32/pulseaudio/modules/module-rtp-recv.so
/usr/lib32/pulseaudio/modules/module-rtp-send.so
/usr/lib32/pulseaudio/modules/module-rygel-media-server.so
/usr/lib32/pulseaudio/modules/module-simple-protocol-tcp.so
/usr/lib32/pulseaudio/modules/module-simple-protocol-unix.so
/usr/lib32/pulseaudio/modules/module-sine-source.so
/usr/lib32/pulseaudio/modules/module-sine.so
/usr/lib32/pulseaudio/modules/module-stream-restore.so
/usr/lib32/pulseaudio/modules/module-suspend-on-idle.so
/usr/lib32/pulseaudio/modules/module-switch-on-connect.so
/usr/lib32/pulseaudio/modules/module-switch-on-port-available.so
/usr/lib32/pulseaudio/modules/module-systemd-login.so
/usr/lib32/pulseaudio/modules/module-tunnel-sink-new.so
/usr/lib32/pulseaudio/modules/module-tunnel-sink.so
/usr/lib32/pulseaudio/modules/module-tunnel-source-new.so
/usr/lib32/pulseaudio/modules/module-tunnel-source.so
/usr/lib32/pulseaudio/modules/module-udev-detect.so
/usr/lib32/pulseaudio/modules/module-virtual-sink.so
/usr/lib32/pulseaudio/modules/module-virtual-source.so
/usr/lib32/pulseaudio/modules/module-volume-restore.so
/usr/lib32/pulseaudio/modules/module-x11-bell.so
/usr/lib32/pulseaudio/modules/module-x11-cork-request.so
/usr/lib32/pulseaudio/modules/module-x11-publish.so
/usr/lib32/pulseaudio/modules/module-x11-xsmp.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pulseaudio/146b824cf04e121da67545caff4ede65bbbb3936
/usr/share/package-licenses/pulseaudio/24b8a642abc0e34765a795aef5ce10475e17574b

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/pacat.1
/usr/share/man/man1/pactl.1
/usr/share/man/man1/padsp.1
/usr/share/man/man1/pamon.1
/usr/share/man/man1/paplay.1
/usr/share/man/man1/parec.1
/usr/share/man/man1/parecord.1
/usr/share/man/man5/pulse-client.conf.5

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/user/pulseaudio-x11.service

%files locales -f pulseaudio.lang
%defattr(-,root,root,-)

